# .github/workflows/ci.yml

name: Build and Test Hardened Azure Image

on:
  push:
    paths:
      - 'packer/**'
      - 'boundary/**'
      - 'netfilter/**'
      - 'scripts/**'
      - '.github/workflows/ci.yml'
  pull_request:

jobs:
  build-packer-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      - name: Validate Packer Templates
        run: |
          cd packer/templates
          packer init .
          packer validate -var-file=../../variables.pkrvars.hcl ubuntu2204-azure.pkr.hcl

      - name: Build Azure Image
        run: |
          cd packer/templates
          packer build -var-file=../../variables.pkrvars.hcl ubuntu2204-azure.pkr.hcl
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Run OpenSCAP Hardening Script
        run: |
          cd packer/scripts
          bash hardening.sh

  boundary-setup-test:
    needs: build-packer-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Shell Script Linting
        run: |
          find . -name "*.sh" -exec bash -n {} \;